services:
  api:
    build: .
    container_name: elai_api
    ports:
      - "5001:5000"
    environment:
      - MODEL_PATH=models/Model.pkl
      - THRESHOLD=0.10
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=elai
      - MONGO_COLLECTION=predictions
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: elai_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: